using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8D5B66C5CC033F9
{
	// Script generated by Pega Robotics Studio 8.0.1087.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8D5B66C5CC033F9")]
	public sealed class Script
	{
		public string NumberToCell(int number)
		{
			int asciiA = 65;
			int asciiNumber = asciiA + (number - 1);
			char c = Convert.ToChar(asciiNumber);
			return c + "";
		}
		public void MoveFile(String FilePath, String ToDir) 
		{
			if(!Directory.Exists(ToDir)) 
			{
				Directory.CreateDirectory(ToDir);
			}
			string fileName = Path.GetFileName(FilePath);
			string ToFilePath = ToDir + Path.DirectorySeparatorChar + fileName;
			if(File.Exists(ToFilePath))
			{
				File.Delete(ToFilePath);
			}
			File.Move(FilePath, ToFilePath);
		}	
	}
}
